# Generated by Django 3.1.7 on 2021-04-08 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='orderproduct',
            old_name='order',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='orderproduct',
            old_name='product',
            new_name='product_id',
        ),
    ]
