version: "3.7"

services:

    db:
        container_name: db
        build:
            context: ./db
            dockerfile: Dockerfile
        ports:
            - 5432:5432    
        env_file: 
            - ./db/.env.dev
        volumes: 
            - pg_data:/var/lib/postgresql/data
        networks: 
            - backend
    django:
        container_name: django
        build:
            context: ./ecommerce
            dockerfile: Dockerfile.dev
        env_file: 
            - ./ecommerce/.env.dev
        ports:
            - 8000:8000
        volumes:
            - ./ecommerce/:/app
        command: python manage.py runserver 0.0.0.0:8000
        networks: 
            - backend
        links:
            - db:db
        depends_on:
            - db
        

volumes:    
    pg_data:

networks: 
    backend:
        driver: bridge

