# Generated by Django 3.1 on 2021-04-11 18:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='product_id')),
                ('name', models.CharField(max_length=100, verbose_name='product name')),
                ('price', models.FloatField(verbose_name='price')),
                ('description', models.TextField(null=True, verbose_name='description')),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='stock quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
            options={
                'db_table': 'product',
                'ordering': ['-created_at'],
            },
        ),
    ]
