FROM python:3.8.3-alpine

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

COPY ./requirements.txt /requirements.txt

RUN apk add --update --no-cache postgresql-client

RUN apk add --update --no-cache --virtual .tmp-build-deps \
	gcc libc-dev linux-headers postgresql-dev

RUN pip install -r /requirements.txt \
    && pip install --upgrade pip

RUN apk del .tmp-build-deps

RUN mkdir app

WORKDIR /app/

COPY . .
